[package]
name = "async-rt-new"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spin = { version = "0.9.3", default-features = false, features = ["mutex", "spin_mutex"] }